apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: local-code-interpreter

resources:
  - namespace.yaml
  - configmap.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml

labels:
  - pairs:
      app.kubernetes.io/name: local-code-interpreter
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
