apiVersion: v1
kind: Service
metadata:
  name: local-code-interpreter
  namespace: local-code-interpreter
  labels:
    app.kubernetes.io/name: local-code-interpreter
    app.kubernetes.io/component: service
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: local-code-interpreter
  ports:
    - name: http
      port: 8090
      targetPort: http
      protocol: TCP
